title: Lacaml
description: OCaml bindings for BLAS/LAPACK (high-performance linear algebra Fortran libraries)
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
